#!/usr/bin/env php
<?php
/**
 * Generate translations source file from JSON message presets
 *
 * This script scans all JSON files in the messages/ directory and extracts
 * translatable strings, generating a PHP file that WP-CLI can scan for .pot creation.
 *
 * Usage: php dev/generate-translations.php
 */

// Determine paths
$script_dir = dirname(__FILE__);
$plugin_dir = dirname($script_dir);
$messages_dir = $plugin_dir . '/messages/';
$output_file = $script_dir . '/translations-source.php';

// Scan for JSON files (skip decline_urls.json)
$json_files = glob($messages_dir . '*.json');
$json_files = array_filter($json_files, function($file) {
    return basename($file) !== 'decline_urls.json';
});

if (empty($json_files)) {
    echo "Warning: No JSON files found in {$messages_dir}\n";
    exit(0);
}

// Start building output
$output = "<?php\n";
$output .= "/**\n";
$output .= " * Auto-generated translation source strings from JSON presets\n";
$output .= " * DO NOT EDIT MANUALLY - Generated by messages/generate-translations.php\n";
$output .= " * \n";
$output .= " * This file is never executed - it only exists for string extraction to .pot file\n";
$output .= " */\n\n";
$output .= "if ( ! defined( 'ABSPATH' ) ) exit;\n\n";

$strings_added = 0;
$files_processed = 0;

foreach ($json_files as $json_file) {
    $basename = basename($json_file);
    $json_content = file_get_contents($json_file);
    $data = json_decode($json_content, true);

    if (!$data) {
        echo "Warning: Could not parse {$basename}\n";
        continue;
    }

    $output .= "// {$basename}\n";

    // Extract translatable strings
    $translatable_keys = [
        'message_label',
        'title',
        'message',
        'legal'
    ];

    foreach ($translatable_keys as $key) {
        if (isset($data[$key]) && !empty($data[$key])) {
            $string = $data[$key];
            // Escape single quotes and backslashes
            $escaped = addslashes($string);
            $output .= "__( '{$escaped}', 'lrob-age-gate' );\n";
            $strings_added++;
        }
    }

    $output .= "\n";
    $files_processed++;
}

// Write output file
file_put_contents($output_file, $output);

echo "✓ Generated {$output_file}\n";
echo "✓ Processed {$files_processed} JSON file(s)\n";
echo "✓ Extracted {$strings_added} translatable string(s)\n";

exit(0);
