<?php
/**
 * Auto-generated translation source strings from JSON presets
 * DO NOT EDIT MANUALLY - Generated by messages/generate-translations.php
 * 
 * This file is never executed - it only exists for string extraction to .pot file
 */

if ( ! defined( 'ABSPATH' ) ) exit;

// adult.json
__( 'Adult Content', 'lrob-age-gate' );
__( 'Age Verification', 'lrob-age-gate' );
__( 'You must be at least {age} years old to access this site. By entering, you confirm that you meet this age requirement.', 'lrob-age-gate' );
__( 'This content is restricted to adults only. Access by minors is prohibited.', 'lrob-age-gate' );

// alcohol.json
__( 'Alcohol', 'lrob-age-gate' );
__( 'Age Verification', 'lrob-age-gate' );
__( 'You must be at least {age} years old to access this site. By entering, you confirm that you meet this age requirement.', 'lrob-age-gate' );
__( 'The sale of alcohol to minors is prohibited. Alcohol abuse is dangerous for your health.', 'lrob-age-gate' );

// cannabis.json
__( 'Cannabis / CBD', 'lrob-age-gate' );
__( 'Age Verification', 'lrob-age-gate' );
__( 'You must be at least {age} years old to access this site. By entering, you confirm that you meet this age requirement.', 'lrob-age-gate' );
__( 'Access to cannabis-related content is restricted to adults where permitted by law.', 'lrob-age-gate' );

// firearms.json
__( 'Firearms', 'lrob-age-gate' );
__( 'Age Verification', 'lrob-age-gate' );
__( 'You must be at least {age} years old to access this site. By entering, you confirm that you meet this age requirement.', 'lrob-age-gate' );
__( 'Access to firearm-related content is restricted to adults of legal age. Always comply with local laws and regulations.', 'lrob-age-gate' );

// gambling.json
__( 'Gambling', 'lrob-age-gate' );
__( 'Age Verification', 'lrob-age-gate' );
__( 'You must be at least {age} years old to access this site. By entering, you confirm that you meet this age requirement.', 'lrob-age-gate' );
__( 'Gambling is prohibited for minors and may be subject to licensing rules. Gamble responsibly.', 'lrob-age-gate' );

// gaming.json
__( 'Gaming', 'lrob-age-gate' );
__( 'Age Verification', 'lrob-age-gate' );
__( 'You must be at least {age} years old to access this site. By entering, you confirm that you meet this age requirement.', 'lrob-age-gate' );
__( 'Online gaming content may be restricted for minors (e.g., playtime limits, age ratings, loot box rules).', 'lrob-age-gate' );

// medication.json
__( 'Medication', 'lrob-age-gate' );
__( 'Age Verification', 'lrob-age-gate' );
__( 'You must be at least {age} years old to access this site. By entering, you confirm that you meet this age requirement.', 'lrob-age-gate' );
__( 'This content concerns medication. Some products are restricted to adults and require prescriptions.', 'lrob-age-gate' );

// tobacco.json
__( 'Tobacco', 'lrob-age-gate' );
__( 'Age Verification', 'lrob-age-gate' );
__( 'You must be at least {age} years old to access this site. By entering, you confirm that you meet this age requirement.', 'lrob-age-gate' );
__( 'The sale of tobacco to minors is prohibited. Smoking harms your health.', 'lrob-age-gate' );

// violence.json
__( 'Violent or Sensitive Content', 'lrob-age-gate' );
__( 'Age Verification', 'lrob-age-gate' );
__( 'You must be at least {age} years old to access this site. By entering, you confirm that you meet this age requirement.', 'lrob-age-gate' );
__( 'This content may include scenes of violence or sensitive material not suitable for minors.', 'lrob-age-gate' );

